#
# Makefile for SNT8100FSR driver
#
# by Sentons Inc.
#

obj-$(CONFIG_SENSORS_SNT8100FSR) += snt8100fsr.o
snt8100fsr-objs :=  crc.o \
                    customize.o \
                    device.o \
                    event.o \
                    file.o \
                    firmware.o \
                    input_device.o \
                    i2c_bus.o \
                    spi_bus.o \
                    serial_bus.o \
                    irq.o \
                    main.o \
                    memory.o \
                    sysfs.o \
                    utils.o \
                    workqueue.o \
